version: '3.7'
services:
  
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/apogeu
      - ./backend/static:/usr/src/apogeu/backend/static
  
  nginx:
    image: nginx:latest
    volumes:
      - ./backend/static:/usr/src/apogeu/backend/static
